### PR TITLE
Add config server

### PR DESCRIPTION
**Pull request by crazyfrozenpenguin**
Introduce simple dynamic configuration server and client.

This is an initial solution that uses @cescoffier [vertx-configuration](https://github.com/cescoffier/vertx-configuration-service/blob/master/vertx-configuration/src/main/asciidoc/java/index.adoc)

It adds a simple singleton based solution to facilitate the configuration of specialized handlers every-time there is a configuration initialization or update. I've added a Log4j configuration service handler as an example.

Issue #9

### CODE REVIEW

**Comment by crazyfrozenpenguin** [comment]
@sczyh30, this build will fail in Travis because @cescoffier vertx-configuration has no public releases yet. Make sure you checkout his project and build the snapshot first.

Once you have done that, build this project branch.

The docker-composer will launch an httd server mounted with an external volume to __./docker/config-server__.

As an example, a configuration service was added to the inventory-microservice. When the microservice starts, a ConfigurationService is setup with a HTTP store to check the __http://configserver:80/inventory-microservice/docker.json__ on 20 seconds intervals.

Handlers will be called for:
 - __Initialization__ - first time the configuration is fetched from the server
 - __Updates__ - subsequent times whenever a configuration change is detected from the server

The inventory-microservice is set with the log4j handlers that look for the __"log4j.config.uri"__ configuration property. Try changing this property in __./docker/config-server/inventory-microservice/docker.json__ to either log4j-console.xml or log4j-gelf.xml and watch how log4j appenders are reconfigured without having to restart the server.

I've added a log to "inventory-microservice/:product" REST call to facilitate visualization. Just hit:
"http://<docker-host>:8086/foo" to emit a log entry to the currently configured appender.

**Comment by cescoffier** [comment]
Just pushed the configuration service to  https://oss.sonatype.org/content/repositories/snapshots/

**Comment by crazyfrozenpenguin** [comment]
@cescoffier, thanks.
@sczyh30, I've added Sonatype's snapshot repo to project's main pom.
Travis should pass now.

**Comment by crazyfrozenpenguin** [comment]
After having a second look into the implemented helper it just made sense to provide a Rx Observable that emits new configs to interested subscribers. A Log4J subscriber was added to process Log4J changes.

The code becomes much simpler and cleaner.

**Comment by crazyfrozenpenguin** [comment]
@sczyh30 , Is there any plan to do session tracking? In other words, is anyone aware if Vertx provides a way to track session requests through logging the eventbus message submission/reception, etc.
It would be nice to get to Kibana and quickly visualize the "tracks" of a given session throughout an application.

**Comment by sczyh30** [comment]
Many thanks! I'll update the documentation these days.

**Pull request merged**
