### PR TITLE
Introduce ELK based logging

### LINKED ISSUE #3: Add ELK logging integration
Add ELK logging integration in the microservice blueprint.

### PR DESCRIPTION
**Pull request by crazyfrozenpenguin**
Logging done through slf4j-log4j bridge and logstash-gelf

Fixes #3.

### CODE REVIEW

**Comment by sczyh30** [comment]
Hi, I failed to run the whole application on Linux due to some error of `elasticsearch` container:

```
elasticsearch_1               | ERROR: bootstrap checks failed
elasticsearch_1               | max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
```

Maybe the `vm.max_map_count` property should be set to 262144 or higher?

**Comment by crazyfrozenpenguin** [comment]
@sczyh30, yes. This is a known issue on the latest elasticsearch docker image.

There are instructions in the README.md of the [elk](https://github.com/crazyfrozenpenguin/vertx-blueprint-microservice/tree/elk) branch for it.

Let me know if you have any questions.

**Comment by sczyh30** [comment]
I've modified `vm.max_map_count` of the host Linux system and it works. Thanks! LGTM.

@pmlopes @cescoffier can you have a review of this? I don't know whether this solution is in best performance and suitable for using in production...

**Comment by crazyfrozenpenguin** [comment]
@sczyh30 and others, a side note that it might be of interest. Log4j2 files can be provided in different formats other than xml (e.g. yml and json). In addition, configuration file lookup can be overwritten through `log4j.configurationFile` system property. If the system property is not set, then it will fallback and look in the classpath for it.

The good part is the the following is legal: `-Dlog4j.configurationFile=http://configserver/log4j2.json`

This means that we can have a central configuration service where microservices can fetch their configuration without having to go through all systems to just reconfigure their logging.

The monitor-dashboard could offer (or be the gateway to) such configuration service and allow instances to be restarted.

Some food for thought.

**Comment by sczyh30** [comment]
@crazyfrozenpenguin yeah, I also thought of such an externalized configuration service for the microservice architecture. One example is [spring-cloud/spring-cloud-config](https://github.com/spring-cloud/spring-cloud-config). And maybe we can integrate with [vertx-configuration-service](https://github.com/cescoffier/vertx-configuration-service)?

**Comment by crazyfrozenpenguin** [comment]
Nice that vertx team is working on its own configuration service. Noticed that @cescoffier as been working. Maybe he can share some ideas/views with us.

I'll definitely be having a look in vertx-configuration-service sometime soon. Could not find any documentation/example for it yet. Is there any?

**Comment by sczyh30** [comment]
The documentations are generated by Vert.x Docgen. They are in each `src/main/asciidoc/java/index.adoc` directory. (e.g. documentation of vertx-configuration-service is in [vertx-configuration-service](https://github.com/cescoffier/vertx-configuration-service/blob/master/vertx-configuration/src/main/asciidoc/java/index.adoc).

I'll also have a look of ` vertx-configuration-service` these days :-)

**Comment by sczyh30** [comment]
I've opened a new issue for configuration service: #9

**Comment by sczyh30** [comment]
Thanks a lot! :-)

**Pull request merged**
